version: "3.8"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      SA_PASSWORD: "Thienlong12345@"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
  redisRateLimit:
    image: redis:latest
    ports:
      - "6379:6379"
